version: "3"
services:
  jupyterlab:
        build: /users/Yuta_Nakamura/web/dockertest/jupyterlab
        user: root
        ports:
          - "80:8888"
        volumes:
          - "./work:/home/jovyan/work" # ← notebookをホストと共有したいディレクトリをマウント
        environment:
          NB_UID: 500 
          GRANT_SUDO: "yes"
        command: start.sh jupyter lab